# Generated by Django 3.2.4 on 2021-06-16 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panaderia', '0002_auto_20210616_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Arina', 'Arina'), ('Azucar', 'Azucar'), ('Manteca', 'Manteca'), ('Levadura', 'Levadura')], max_length=20)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComprasProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(max_length=7)),
                ('cantidad', models.IntegerField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panaderia.inventarioproducto')),
            ],
        ),
    ]
