# Generated by Django 3.2.4 on 2021-06-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0005_alter_comprasproducto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasproducto',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
