# Generated by Django 3.2.4 on 2021-06-17 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0006_alter_comprasproducto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasproducto',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
