# Generated by Django 3.2.4 on 2021-06-17 02:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0008_remove_comprasproducto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasproducto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 2, 28, 25, 200830, tzinfo=utc)),
        ),
    ]
