# Generated by Django 3.2.4 on 2021-06-17 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0009_comprasproducto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasproducto',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='comprasproducto',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 19, 29, 19, 895029, tzinfo=utc)),
        ),
    ]
