# Generated by Django 3.2.4 on 2021-06-18 13:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0011_auto_20210617_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(choices=[('Quintal', 'Quintal'), ('Libra', 'Libra')], max_length=7)),
                ('cantidad', models.PositiveIntegerField(blank=True, default=0)),
                ('fecha', models.DateTimeField(default=datetime.date.today)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panaderia.inventarioproducto')),
            ],
        ),
    ]
