# Generated by Django 3.2.4 on 2021-06-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0013_auto_20210618_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='cantidad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
